### ISSUE TITLE
'pax' command not found

### ISSUE THREAD

**Issue by PaulBatchelor** [oasislinux/oasis#10]
Currently trying to follow the [wiki](https://github.com/oasislinux/oasis/wiki/Install)

This happens with scripts/fetch-curl.sh:

> ./scripts/fetch-curl.sh: line 34: pax: not found
> FAILED: pkg/byacc/fetch 
> sh ./scripts/fetch-curl.sh pkg/byacc && touch pkg/byacc/fetch
> ninja: build stopped: subcommand failed.

It seems I need to install the "pax" utility on my system. This is proving to be very difficult to do on Alpine (it doesn't exist in the repo, and the sources have an archaic autotools system).

Is there any possible workaround for this?

**Comment by michaelforney** [comment]
Yep, the workaround is to install `bsdtar` from libarchive-tools, and set `PAXREAD=bsdtar -x -f -`. This is what the continuous build script does, which runs from an Alpine image.

**Comment by PaulBatchelor** [comment]
Awesome. I think that worked.
