### ISSUE TITLE
Prismlauncher does not work

### ISSUE THREAD

**Issue by ErnestNoga** [oasislinux/oasis#102]
I am currently attempting to daily drive oasis linux, mostly successfully so, but I have been unable to get prismlauncher to work. I tried both nix and flatpak (installed through nix). Whenever I try to launch minecraft in Prismlauncher I get a message which says that GLX extension could not be found, I have been able to fix that by adding libglvnd `/lib` to `LD_LIBRARY_PATH` but I get another crash which says that `libGL.so.1` could not be found. I believe this is an issue on oasis linux's side so I'm reporting it here. I'm stumped on what to do, I tried copying that library to system /lib and that did not work. Thanks for any help.

**Comment by apprehensions** [comment]
Oasis is not for you.

**Comment by apprehensions** [comment]
As someone who was once in your position, give Alpine a shot.

**Comment by michaelforney** [comment]
oasis is a statically linked system. OpenGL drivers are designed around dynamic linking, so you'll need to install that software some other way. Note also that wld has very limited support for hardware acceleration, and uses software rendering on other GPUs. For those other GPUs, only wl_shm is supported, which means mesa is likely to fall back to software 3D rendering, which might be very slow, so you'll probably want to use some other display server as well.

**Comment by michaelforney** [comment]
I don't play games that often, but when I do, I use xorg and mesa installed with pkgsrc, and flatpak steam.

**Comment by michaelforney** [comment]
I used steam with flatpak. Nix should work too.

In general though, to get the dynamic loader to find libraries, you need to do one of
- Build the software in question with a `DT_RUNPATH` header listing directories in which to search for shared libraries. This is what pkgsrc does.
- On musl systems, add the directory to a file `/etc/ld-musl-x86_64.path`. On glibc systems, I think the equivalent is `ld.so.conf`.
- Set the `LD_LIBRARY_PATH` environment variable.

This is well outside the scope of oasis, though, so I'm going to close this issue. Keep in mind that the github issue tracker is for reporting issues in oasis, not a support channel. You are welcome to ask questions on IRC. If I have the time, I or others might be able to help out.
