### ISSUE TITLE
Can I install individual packages?

### ISSUE THREAD

**Issue by xplshn** [oasislinux/oasis#106]
How?

**Comment by michaelforney** [comment]
Can you clarify your question? I don't really understand what you mean.

**Comment by xplshn** [comment]
How can I install a specific package without installing a set? Like for example, the man pages

**Comment by michaelforney** [comment]
Here's the documentation:
```lua
                -- Each entry contains a list of packages, a list of patterns
                -- matching files to include from those packages, and a list of
                -- patterns matching files to exclude. If no patterns are
                -- specified, all files from the package are included.
		{sets.core, exclude={'^include/', '^lib/.*%.a$'}},
```

Sets are literally just convenient lists of packages (see `sets.lua`). To add `man-pages-posix`, add it to the list:

```lua
{sets.core, 'man-pages-posix', exclude={'^include/', '^lib/.*%.a$'}},
```

**Comment by xplshn** [comment]
Thanks for the explanation, I couldn't understand the comment which explained it
