### ISSUE TITLE
Replacements

### ISSUE THREAD

**Issue by xplshn** [oasislinux/oasis#107]
I propose we use the upstream `ubase` and ditch `linux-utils` (unless there is a motive behind keeping an outdated `ubase` and a mostly up-to-date `linux-utils`.)

Also, is there any reason `sbase` isn't included?

Thanks! Awesome project!

**Comment by michaelforney** [comment]
> I propose we use the upstream `ubase` and ditch `linux-utils` (unless there is a motive behind keeping an outdated `ubase` and a mostly up-to-date `linux-utils`.)

Until very recently, it was the other way around. Upstream ubase had no maintainer and our oasis branch was more up to date. It will be updated to latest upstream when someone gets around to it.

I don't know what you mean by `linux-utils`. If you mean `util-linux`, we build only `fdisk`, `nsenter`, and `losetup` from `util-linux`. These tools are not available from `ubase`. If we removed them, there would be no way to partition disks or setup loopback devices.

> Also, is there any reason `sbase` isn't included?

It is included. I'm not sure why you think it's missing.

**Comment by michaelforney** [comment]
In the future, please don't use the issue tracker for support or to ask questions. The mailing list and IRC channel are the place for this.

**Comment by xplshn** [comment]
Sorry for the dumb mistakes, I was sleepy at the time of writing, thanks for answering everything in a kind way.
