### ISSUE TITLE
Ninja Commit Failing

### ISSUE THREAD

**Issue by 7z3m** [oasislinux/oasis#121]
Hello folks, sorry to bother you. 
Is this a C toolchain issue? pretty much the only thing I'm not sure of. 

error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0
error: 3975 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/git/git' into submodule path '/mnt/oasis/root/src/oasis/pkg/git/src' failed
Failed to clone 'pkg/git/src'. Retry scheduled

FAILED: out/probe/SIZEOF_LONG
sh ./scripts/probe-size.sh SIZEOF_LONG out/probe/SIZEOF_LONG x86_64-linux-musl-cc -Os -fPIE -pipe -c -o /dev/null -x c probe/SIZEOF_LONG
==> trying SIZEOF_LONG=8...
E: ./scripts/probe-size.sh[18]: x86_64-linux-musl-cc: inaccessible or not found
==> trying SIZEOF_LONG=4...
E: ./scripts/probe-size.sh[18]: x86_64-linux-musl-cc: inaccessible or not found
==> trying SIZEOF_LONG=2...
E: ./scripts/probe-size.sh[18]: x86_64-linux-musl-cc: inaccessible or not found
==> trying SIZEOF_LONG=1...
E: ./scripts/probe-size.sh[18]: x86_64-linux-musl-cc: inaccessible or not found
./scripts/probe-size.sh: could not determine SIZEOF_LONG
[3/6656] sh ./scripts/probe-size.sh SIZEOF_SIZE_T out/probe/SIZEOF_SIZE_T x86_64-linux-musl-cc -Os -fPIE -pipe -c -o /dev/null -x c probe/SIZEOF_SIZE_T

**Comment by hovercats** [comment]
> E: ./scripts/probe-size.sh[18]: x86_64-linux-musl-cc: inaccessible or not found

check if `x86_64-linux-musl-cc` is in PATH.
either build a crosscompiler yourself (like musl-cross-make), or use a prebuilt one from musl.cc

**Comment by 7z3m** [comment]
> > E: ./scripts/probe-size.sh[18]: x86_64-linux-musl-cc: inaccessible or not found
> 
> check if `x86_64-linux-musl-cc` is in PATH, as it appears to not be in PATH. you need to either build a crosscompiler yourself (like musl-cross-make), or use a prebuilt one from musl.cc if you didnt already do that.

that's pretty much what i thought, so i added the prebuilt cc folder itself to path in my .profile. just to be 100% sure. i need to give it another shot i guess.

**Comment by michaelforney** [comment]
Closing. Reopen if installing a musl toolchain doesn't fix things.
