### ISSUE TITLE
Provide a Github Action in this repo to produce a rootfs + bootable image (would be cool to simply compile everything on good hardware and then boot and manually install to your pc)

### ISSUE THREAD

**Issue by xplshn** [oasislinux/oasis#122]
Compiling locally takes ages on my Athlon II PC, and its generally not a good experience having to wait for the build process to get halfway to then stop because you are missing a dependency. Its a real pain. Iglunix provides a github action to build a ROOTFS and I think that would make Oasis easier to compile and it'd be very handy to test changes too.

**Comment by TheMBL09898** [comment]
https://github.com/oasislinux/root-x86_64

**Comment by xplshn** [comment]
@TheMBL09898 There are no actions/workflows in that repo. Its just a dump of a +5 month old rootfs

**Comment by michaelforney** [comment]
The actions/workflows are in this repo, but we use builds.sr.ht, not github actions.

The repository that @TheMBL09898 linked is automatically built by https://github.com/oasislinux/oasis/blob/master/.build.yml. 3 months ago is just when the last build succeeded. It seems there have been some git repositories going down (xz, freedesktop), so submodules need to have their paths updated.

If you don't want to build yourself, then using that is the best option. Also note that there's no reason you have to build oasis on the same computer you run it on. You can just point the git remote of system running oasis to the repository built by the fast computer.

You mentioned missing dependencies, can you provide an example? The oasis build is very self contained and only has a few actual build dependencies which are listed in the README.

**Comment by michaelforney** [comment]
> It seems there have been some git repositories going down (xz, freedesktop), so submodules need to have their paths updated.

Fixed in c26adb5386edeb7bd09e79da969771aa3a5053c5, and automatic root-x86_64 build has succeeded.

**Comment by xplshn** [comment]
> You mentioned missing dependencies, can you provide an example? The oasis build is very self contained and only has a few actual build dependencies which are listed in the README.

I have KISS Linux on my Athlon computer, I wanted to replace KISS with Oasis, but now that you mention it, I could install Alpine, which packages everything I need to build Oasis and then build Oasis. I was having issues with `pigz` and `Lua`, I couldn't get them working under KISS. I'll try to get Oasis running again when I have the time. Thanks for answering this.

> If you don't want to build yourself, then using that is the best option. Also note that there's no reason you have to build oasis on the same computer you run it on. You can just point the git remote of system running oasis to the repository built by the fast computer.

So, in short, what do I have to do? Fork the repo that >TheMBL09898 linked and run the action/script? Or do I have to fork both repos (this one, and the rootfs one)?

**Comment by xplshn** [comment]
Oh, so. I have to run the build locally too? Is there no way to use an action runner like Github's? None of my PCs are suited to build the Linux kernel while using them, building in my i3 laptop takes more than a day (its 7th gen and gets really hot while running).

(55% CPU usage with just a YT video and 4 tabs open in FF)
![image](https://github.com/user-attachments/assets/66180899-acc6-4d12-b802-4527035491b9)

**Comment by xplshn** [comment]
@michaelforney I found a repo secret stored on on .build.yml, you should rotate that API key before someone uses it with ill intent

**Comment by rnpnr** [comment]
> @michaelforney I found a repo secret stored on on .build.yml, you should rotate that API key before someone uses it with ill intent

Thats not a secret, its a UUID used by the sourcehut builder to find the actual secret in Michael's account (probably an SSH key for pushing to Github).

**Comment by xplshn** [comment]
a, thanks

**Comment by TheMBL09898** [comment]
> So, in short, what do I have to do? Fork the repo that TheMBL09898 linked and run the action/script? Or do I have to fork both repos (this one, and the rootfs one)?

Use this: https://codeberg.org/Potosi/deploy-scripts/src/branch/master/oasislinux-install.sh

The script is quite messy as it used my oasislinux fork which no longer exists, but other than that you just have to change a couple of variables to make it work (I use it all the time).
```
SETS="core desktop devel extra media net"
OASIS_GIT=https://github.com/oasislinux/oasis
SYSROOT=https://github.com/oasislinux/root-x86_64
```

I use my own clang/llvm toolchain instead of the one provided by mcf, you might want to change `git remote add toolchain https://codeberg.org/Potosi/toolchain.git` to `git remote add toolchain https://github.com/oasislinux/toolchain` and `git config --add branch.master.merge toolchain/clang-x86_64-unknown-linux-musl-native` to `git config --add branch.master.merge toolchain/master`, although you can just install both (or none).

You might want to change `git clone -b etc "$SYSROOT" --depth 1 etc/` to `git clone --depth 1 https://github.com/oasislinux/etc`, or you can just use the tarball as suggested in the wiki.

Make sure to also modify the script to put your own user name and time zone as well. After running this, all that's left over is just installing your bootloader and kernel. Good luck!

**Comment by xplshn** [comment]
Thanks, I will try this!

**Comment by xplshn** [comment]
I was hoping I'd be able to build Oasis using an action, but I'll rely on your script for now, thanks for sharing.

**Comment by michaelforney** [comment]
> I was hoping I'd be able to build Oasis using an action&worker, but I'll rely on your script for now, thanks for sharing.

@TheMBL09898's script uses the root fs built by builds.sr.ht. Is that not what you're looking for?

If you want something else, you could also fork the repository and modify .build.yml to your taste (i.e. change packages, port to github actions).

**Comment by xplshn** [comment]
> !TheMBL09898's script uses the root fs built by builds.sr.ht. Is that not what you're looking for?
If you want something else, you could also fork the repository and modify .build.yml to your taste (i.e. change packages, port to github actions).

So, what I need to do if I want to trigger builds of Oasis myself is;
 -> Register at sourcehut
 -> Fork this repo
 -> Add my SSH key to the .build.yml?

**Comment by michaelforney** [comment]
> So, what I need to do if I want to trigger builds of Oasis myself is; -> Register at sourcehut -> Fork this repo -> Add my SSH key to the .build.yml?

Sure. You could also set it up to run as a github action if that's your preference.

But it's still a bit unclear to me what your goal is. The sr.ht builds run automatically and deploy to the root-x86_64 repository for every commit. If you run the same script with your own github action/builds.sr.ht job, you'll get the same output. Since it seems like that's not what you want, I guess you want to make some of your own changes (perhaps package/file selection in config.lua, or patches/new packages in your oasis fork?).

**Comment by xplshn** [comment]
Yeah, I was hoping I'd get to choose which packages to install. Thanks for all the clarification.

**Comment by xplshn** [comment]
@michaelforney Is the secret on .build.yml of SSH type? I suppose it points to the key/password/token of the github repo that contains the rootfs?

**Comment by LaithOsama** [comment]
If you're still interested, I ported the sr.ht build script to Github

```
name: Oasis build

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  SETS: core extra devel media net desktop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bison curl libarchive-tools lua5.1 nasm ninja-build wayland-protocols libwayland-dev libpng-dev
        git config --global user.name "oasis"
        git config --global user.email "oasis"
        git clone --mirror https://github.com/oasislinux/root-x86_64 root-x86_64.git
        curl -LO http://musl.cc/x86_64-linux-musl-cross.tgz
        tar xzf x86_64-linux-musl-cross.tgz
        echo "$HOME/x86_64-linux-musl-cross/bin:$HOME/bin" >> $GITHUB_PATH
        echo "PATH=$PWD/x86_64-linux-musl-cross/bin:$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Build
      run: |
        cat >config.lua <<EOF
        return {
          builddir='out',
          fs=dofile 'fs.lua',
          target={platform='x86_64-linux-musl', cflags='-Os -fPIE -pipe', ldflags='-s -static-pie', mc='6m', pie=true},
          host={cflags='-pipe', ldflags=''},
          repo={path='$PWD/root-x86_64.git', flags='--bare', tag='tree', branch=os.getenv('SET')},
        }
        EOF
        echo 'return {exclude={}}' >fs.lua
        SET=all lua setup.lua
        ninja out/pkg/mc/bin/6m out/pkg/mc/bin/muse
        mkdir $HOME/bin
        cp out/pkg/mc/bin/6m out/pkg/mc/bin/muse $HOME/bin
        ninja
        cat >fs.lua <<EOF
        local sets = dofile 'sets.lua'
        local set = os.getenv('SET')
        local spec = {sets[set]}
        if set ~= 'devel' then
          spec.exclude = {'^include/', '^lib/.*%.a$'}
        end
        return {spec}
        EOF
        for SET in $SETS ; do
          export SET
          lua setup.lua
          ninja commit
        done
    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        git -C root-x86_64.git push https://x-access-token:${TOKEN}@github.com/oasislinux/root-x86_64.git $SETS

```

All you need to do is create a new repository (eg `root-x86_64`) and create a branch for each set, then paste the script above to `[your oasis fork root]/.github/workflows/build.yml`. Don't forget to setup token secret (`In your repository, go to Settings > Secrets > Actions`).
However, while it tasted and works, this is the first time I've made something like this, it probably needs to be checked and reviewed.

Best wishes.

**Comment by xplshn** [comment]
> If you're still interested, I ported the sr.ht build script to Github
> 
> ```
> name: Oasis build
> 
> on:
>   push:
>     branches: master
>   pull_request:
>     branches: master
> 
> env:
>   SETS: core extra devel media net desktop
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     
>     steps:
>     - uses: actions/checkout@v3
>       with:
>         fetch-depth: 0
>         
>     - name: Set up environment
>       run: |
>         sudo apt-get update
>         sudo apt-get install -y bison curl libarchive-tools lua5.1 nasm ninja-build wayland-protocols libwayland-dev libpng-dev
>         git config --global user.name "oasis"
>         git config --global user.email "oasis"
>         git clone --mirror https://github.com/oasislinux/root-x86_64 root-x86_64.git
>         curl -LO http://musl.cc/x86_64-linux-musl-cross.tgz
>         tar xzf x86_64-linux-musl-cross.tgz
>         echo "$HOME/x86_64-linux-musl-cross/bin:$HOME/bin" >> $GITHUB_PATH
>         echo "PATH=$PWD/x86_64-linux-musl-cross/bin:$HOME/bin:$PATH" >> $GITHUB_ENV
>     - name: Build
>       run: |
>         cat >config.lua <<EOF
>         return {
>           builddir='out',
>           fs=dofile 'fs.lua',
>           target={platform='x86_64-linux-musl', cflags='-Os -fPIE -pipe', ldflags='-s -static-pie', mc='6m', pie=true},
>           host={cflags='-pipe', ldflags=''},
>           repo={path='$PWD/root-x86_64.git', flags='--bare', tag='tree', branch=os.getenv('SET')},
>         }
>         EOF
>         echo 'return {exclude={}}' >fs.lua
>         SET=all lua setup.lua
>         ninja out/pkg/mc/bin/6m out/pkg/mc/bin/muse
>         mkdir $HOME/bin
>         cp out/pkg/mc/bin/6m out/pkg/mc/bin/muse $HOME/bin
>         ninja
>         cat >fs.lua <<EOF
>         local sets = dofile 'sets.lua'
>         local set = os.getenv('SET')
>         local spec = {sets[set]}
>         if set ~= 'devel' then
>           spec.exclude = {'^include/', '^lib/.*%.a$'}
>         end
>         return {spec}
>         EOF
>         for SET in $SETS ; do
>           export SET
>           lua setup.lua
>           ninja commit
>         done
>     - name: Deploy
>       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
>       env:
>         TOKEN: ${{ secrets.TOKEN }}
>       run: |
>         git -C root-x86_64.git push https://x-access-token:${TOKEN}@github.com/oasislinux/root-x86_64.git $SETS
> ```
> 
> All you need to do is create a new repository (eg `root-x86_64`) and create a branch for each set, then paste the script above to `[your oasis fork root]/.github/workflows/build.yml`. Don't forget to setup token secret (`In your repository, go to Settings > Secrets > Actions`). However, while it tasted and works, this is the first time I've made something like this, it probably needs to be checked and reviewed.
> 
> Best wishes.

Oh man, Thanks!!! Will report back

**Comment by LaithOsama** [comment]
You are welcome mate.
You can share your error with me here if you stuck, I've been through it all while making this.
I also forgot to say that you have to replace `oasislinux/root-x86_64.git` in the script with your just created repo before using it. With that in mind, I didn't test the rootfs in a hardware yet, but it looks like the mcf's one.

**Comment by xplshn** [comment]
![image](https://github.com/user-attachments/assets/600742ee-b162-477a-8076-524640f6019f)
Maybe you can make your repo public? So that I & just add then token

**Comment by LaithOsama** [comment]
I just deleted it as it got messy after some of the recent experiments.
