### ISSUE TITLE
Suggest: --enable-new-dtags

### ISSUE THREAD

**Issue by andrewchambers** [oasislinux/oasis#16]
If you have the dynamic linker enabled, I think its best to set --enable-new-dtags in the musl cross make config. This defaults to RUNPATH instead RPATH in .so files.

**Comment by michaelforney** [comment]
binutils is already built so that it uses RUNPATH by default (see the [config.h](https://github.com/oasislinux/oasis/blob/b39004f210b110a4e9d77edf12012f8a4376da49/pkg/binutils/ld/config.h#L10)).

```
$ echo 'int main(void){}' | gcc -x c - -Wl,-rpath,/foo
$ readelf -d a.out | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/foo]
```
