### ISSUE TITLE
Wrong header file name in pkg/awk/gen.lua

### ISSUE THREAD

**Issue by AkiraHasegawa1997** [oasislinux/oasis#17]
In `pkg/awk/gen.lua`, the header file (awkgram.tab.h) has not replaced yet.

This line
```build('maketab', '$outdir/proctab.c', {'$outdir/ytab.h', '|', '$outdir/maketab'})```
should be
```build('maketab', '$outdir/proctab.c', {'$outdir/awkgram.tab.h', '|', '$outdir/maketab'})```.

**Comment by michaelforney** [comment]
Thanks for the report! This is fixed now.
