### ISSUE TITLE
/var is empty.

### ISSUE THREAD

**Issue by Scupake** [oasislinux/oasis#18]
I tried building oasis multiple times, I was successful only twice, and in both attempts /var was empty, I tried running hotplugd but that didn't work. Oh btw, can you please explain how you're supposed to install/build stuff after building the distro?

**Comment by michaelforney** [comment]
What do you expect in `/var`? It only contains a few empty directories by default, which are initially created by the `./libexec/applyperms` step in the install instructions. hotplugd only manages special permissions of /dev (for things like fuse or drm devices). It is not necessary for a working system.

You can select which packages you want to install by modifying config.lua, particularly the `fs` table. If you are asking about software that is not present in the oasis base system, you can use pkgsrc (see the pkgsrc page in the wiki).

**Comment by michaelforney** [comment]
> You can select which packages you want to install by modifying config.lua, particularly the fs table.

Forgot to mention: once you do that, you can rebuild the system (`samu commit`), then merge the changes to / (`git -C / merge`).

**Comment by Scupake** [comment]
>  It only contains a few empty directories by default

For some reason it's completely empty for me, no dirs in it, I'll try running applyperms again.

**Comment by Scupake** [comment]
Tried running it again, I get this error when running it in a chroot: ``fatal: open /dev/null or dup failed: No such file or directory
child process failed``.

And I get this one when running it from the livecd I get this error: ``posix_spawnp: No such file or directory``

(sorry if the answer is obvious, I'm really not good at this)

**Comment by michaelforney** [comment]
> Tried running it again, I get this error when running it in a chroot: `fatal: open /dev/null or dup failed: No such file or directory child process failed`.

When you enter a chroot, you'll usually need to set up some mounts. Something like

```
mount -o bind /dev dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
```

> And I get this one when running it from the livecd I get this error: `posix_spawnp: No such file or directory`

Hmm... that sounds like /libexec/applyperms might not be statically linked. Can you post your config.lua and the output of `readelf -l libexec/applyperms`?

> (sorry if the answer is obvious, I'm really not good at this)

No worries, I know that the install procedure is a bit tricky. I'm working on a new deployment mechanism (instead of git) that should simplify this quite a bit when it is finished.

**Comment by michaelforney** [comment]
> > And I get this one when running it from the livecd I get this error: `posix_spawnp: No such file or directory`
> 
> Hmm... that sounds like /libexec/applyperms might not be statically linked. Can you post your config.lua and the output of `readelf -l libexec/applyperms`?

Actually, nevermind, I think it is probably just that the livecd does not have git installed.

**Comment by Scupake** [comment]
> When you enter a chroot, you'll usually need to set up some mounts. Something like

>mount -o bind /dev dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

Still getting the same error.

>Actually, nevermind, I think it is probably just that the livecd does not have git installed.

Yeah, you're right, I forgot to install the packages when I booted into the livecd today. I don't get any errors now, but /dev is still empty.
![image](https://user-images.githubusercontent.com/61241021/90382833-cf781800-e06e-11ea-9e17-c9ac26bdae1e.png)

**Comment by Scupake** [comment]
I'm doing to rebuilt it again, hope it works this time.

**Comment by michaelforney** [comment]
> > When you enter a chroot, you'll usually need to set up some mounts. Something like
> 
> > mount -o bind /dev dev
> > mount -t proc none /proc
> > mount -t sysfs none /sys
> > mount -t tmpfs none /tmp
> 
> Still getting the same error.

This doesn't make sense to me. Are you sure you bind-mounted /dev into the right location?

> > Actually, nevermind, I think it is probably just that the livecd does not have git installed.
> 
> Yeah, you're right, I forgot to install the packages when I booted into the livecd today. I don't get any errors now, but /dev is still empty.
> ![image](https://user-images.githubusercontent.com/61241021/90382833-cf781800-e06e-11ea-9e17-c9ac26bdae1e.png)

/dev will be empty until you boot up oasis and the devtmpfs gets automounted (via `CONFIG_DEVTMPFS_MOUNT`). When you are in the live CD environment, you instead need to bind-mount the /dev from the host into the dev inside the chroot.

**Comment by michaelforney** [comment]
> I'm doing to rebuilt it again, hope it works this time.

Feel free to join IRC (#oasislinux on freenode) if you run into any problems or have any additional questions.

**Comment by Scupake** [comment]
> you instead need to bind-mount the /dev ***from the host*** into the dev inside the chroot.

Oh, that was it, thanks for answering my questions!
