### ISSUE TITLE
cannot open out/pkg/tz/zoneinfo/Australia/Currie: No such file

### ISSUE THREAD

**Issue by Mordillo98** [oasislinux/oasis#22]
I'm doing a textbook install of OASIS using debian, and everything went well until it tries to install the Australia/Currie timezone.

[4553/5968] 	HASH	100644 share/zoneinfo/Australia/Currie
FAILED: out/root.hash/share/zoneinfo/Australia/Currie 
sh ./scripts/hash.sh out/root.git 100644 share/zoneinfo/Australia/Currie out/pkg/tz/zoneinfo/Australia/Currie >out/root.hash/share/zoneinfo/Australia/Currie
./scripts/hash.sh: 17: ./scripts/hash.sh: cannot open out/pkg/tz/zoneinfo/Australia/Currie: No such file
[4554/5968] 	CC	out/pkg/tz/zic.c.o
ninja: build stopped: subcommand failed.

I checked if I have enough space on HD, which I do on /dev/sdb2.

root@debian:/mnt/src/oasis# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            971M     0  971M   0% /dev
tmpfs           198M  5.6M  192M   3% /run
/dev/sda1        19G  1.8G   16G  11% /
tmpfs           986M     0  986M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           986M     0  986M   0% /sys/fs/cgroup
tmpfs           198M     0  198M   0% /run/user/0
/dev/sdb2       9.8G  1.1G  8.2G  12% /mnt
/dev/sdb1       2.0M   21K  1.9M   2% /mnt/boot
root@debian:/mnt/src/oasis# 

Thx !

**Comment by michaelforney** [comment]
Thanks for the report, should be fixed now. I forgot to regenerate the manifest of zoneinfo files during the last tz update (it doesn't usually change), and didn't notice the removal of the file since it was still left over from the previous build.
