### ISSUE TITLE
commit.sh fatal: Not a valid object name tree

### ISSUE THREAD

**Issue by faithanalog** [oasislinux/oasis#23]
I'm following https://github.com/oasislinux/oasis/wiki/Install

I did the instructions of git init from the oasis template in root, setting this config, and running `ninja commit`

```lua
repo={
	path='../..',
	flags='',
	tag='tree',
	branch='oasis',
}
```

at the end of the build, I'm getting this error:

```txt
[1/1] sh ./scripts/commit.sh ../.. oasis tree out/root.commit
FAILED: out/root.commit
sh ./scripts/commit.sh ../.. oasis tree out/root.commit
fatal: Not a valid object name tree
ninja: build stopped: subcommand failed.
```

the specific line in commit.sh that's failing is https://github.com/oasislinux/oasis/blob/00af93b9625f1c0394f7ea0e869e85713484a198/scripts/commit.sh#L26

I tried creating the oasis branch (root is on master) and then creating an inital commit and tagging it "tree". That did get this command to not error, but it didn't actually help anything because the subsequent merge instructions failed from master, stating oasis was not something that can be merged.

Anyway I'm not enough of a git witch to understand what's actually supposed to be happening to debug this.

**Comment by michaelforney** [comment]
I'm not exactly sure what happened to get into this state.

Here's how it works:
- The default target, `out/root.tree` is built by writing a git tree object to the repository at `config.repo.path`, and tagging this object with the name `git.repo.tag`. If this succeeds, you should be able to run `git -C $repo show tree` and it should show the top-level directories of this tree.
- The `commit` target depends on `out/root.tree`, and is built by making a new commit with the tree specified by `config.repo.tree`, built previously, and parent commit `config.repo.branch`, and then updating the branch to point to this new commit.

Can you try deleting the `tree` tag in the root repository `git tag -d tree`, removing `out/root.tree`, and then running `ninja commit` again?

> That did get this command to not error, but it didn't actually help anything because the subsequent merge instructions failed from master, stating oasis was not something that can be merged.

This is also confusing to me. If `ninja commit` succeeded, then it wrote a branch called `oasis` (or whatever `config.repo.branch` was set too). That error indicates that there is no such branch. Are you sure you ran the git merge from the same repository that `config.repo.path` points to?

**Comment by faithanalog** [comment]
ok yeah i have no idea what happened last night to get it into that state either. Just now I

- deleted the git repo in root and re-init'd it
- deleted everything in `out/` except `out/pkg/`
- re-ran `lua setup.lua`
- re-ran `ninja commit`

and that worked just fine, as did the merge. Thanks for explaining what's going on.
