### ISSUE TITLE
CONFLICT (content): Merge conflict in Makefile

### ISSUE THREAD

**Issue by middleeasternfag** [oasislinux/oasis#26]
`git pull --no-edit https://github.com/oasislinux/linux`
fails at automerging the Makefile with the error in the title. Not sure if I did a mistake or the wiki is outdated. In any case, I will try installing it again.

**Comment by michaelforney** [comment]
Which tag did you check out before the pull? The oasis branch is up to date with v5.13, and I don't get any conflicts when merging the stable point releases.

But anyway, if you run into conflicts you should open the files and resolve them in order to complete the merge.

**Comment by middleeasternfag** [comment]
v5.13.9 and I don't know what exactly I did wrong, doesn't matter anyhow since it works now (I doubt that the fact that it's a Debian Live disk this time makes any difference). In any case, though, I think you should add nasm to the prerequisites since I had to manually install it each time (used live installations each time).

**Comment by michaelforney** [comment]
> In any case, though, I think you should add nasm to the prerequisites since I had to manually install it each time (used live installations each time).

Done: https://github.com/oasislinux/oasis/wiki/Install/_compare/65ce8b813ccbf0167ec045c3fd1a79d853100331...716a11a7953e598970bc015a52a7495a145352f8

**Comment by middleeasternfag** [comment]
Thanks. Another thing I should mention is that `make menuconfig` required me to install oasislinux's netbsd-curses build on the live installation. Just Debian's ncurses library and headers didn't work for me (kept getting the error `/usr/bin/ld: cannot find -lterminfo`).
