### ISSUE TITLE
the gui is barely usable

### ISSUE THREAD

**Issue by RavikumarTulugu** [oasislinux/oasis#29]
The gui started with virtualdesktops and clock. but , nothing would happen on mouse clicks. please give a menu on a mouse click , the gui needs a tonne of improvements before it is usable.

**Comment by harrisonrobin** [comment]
if you are looking for a menu there is the dmenu shipped with oasis. it is launched via a keyboard shortcut and it is used to start gui programs. velox the window manager in oasis is modeled after dwm, which is a keyboard centric tiling window manager. The gui supports using mouse for things like copy paste and plumbing that involve selecting text in some way. However, the keyboard is the predominant input and interaction method. You can modify the shortcuts in the velox config file in /etc folder to suit personal preferences.

**Comment by michaelforney** [comment]
What @harrisonrobin said is correct.

If you don't like how velox works, then patch it to behave how you want. That is the whole point of oasis.

I use velox everyday, which seems to contradict your opinion that it is unusable.

**Comment by RavikumarTulugu** [comment]
ok it was just a feedback.
