### ISSUE TITLE
Recommendation: Shell

### ISSUE THREAD

**Issue by mby** [oasislinux/oasis#33]
What do you think about using [Oil shell](https://www.oilshell.org/) instead of oksh?

**Comment by noocsharp** [comment]
The oasis system is designed to only require a C compiler to build, and only packages Python 3. Oil shell seems to require either a C++ compiler or Python 2 interpreter, which probably makes it a non-starter. Also oasis doesn't have any long shell scripts, or any bash scripts at all, which are where the benefits of Oil are supposed to manifest.

**Comment by michaelforney** [comment]
What @noocsharp said is correct. I don't think the oil shell fits that well with the rest of the system.

We don't have any bash scripts, and rc is available as a non-POSIX shell if you want a slightly better language to write scripts.
