### ISSUE TITLE
Package the kernel with the build system

### ISSUE THREAD

**Issue by BentonEdmondson** [oasislinux/oasis#42]
I went through the install a while ago, and I remember the most tedious part being building the kernel.

It would be nice if it was packaged alongside the other packages. I envision the kernel config settings could then be configured in `config.lua` so that they could be saved to version control, thereby allowing more consistent system rebuilds. Also this system would make kernel updates as automatic as base system utility updates, instead of manual.

What do you think of this idea?

**Comment by TheArchMux** [comment]
How did you get `elfutils` installed?

**Comment by michaelforney** [comment]
The kernel build system is extremely complex. This would be a nightmare to write and maintain.

You can put your kernel `.config` into version control. That's what I do.

@TheGitMux oasis uses elftoolchain, not elfutils.

**Comment by apprehensions** [comment]
You can make generate a build manifest hard-set from the kernels .config configuration and Kbuilds?
