### ISSUE TITLE
What is the password of qemu image?

### ISSUE THREAD

**Issue by azim-sahim** [oasislinux/oasis#43]
I can't really find password for oasis login. It isn't in wiki and it isn't in readme of oasis. I tried to guess, but not successfully. If i just didn't find it, the issue will be that it's really hard to find, if it's really not written anywhere this will be an issue.

**Comment by michaelforney** [comment]
The password is blank (the empty string). I thought this was stated somewhere, but I can't find it either. Sorry about that, I'll update the readme.

**Comment by azim-sahim** [comment]
Thank you! 
Should I close the case? or wait until it is written in reamde

**Comment by azim-sahim** [comment]
oh, sorry. Now i found it. It is in tips of qemu tips. (It would be better if it was in readme, but I don't insist)
