### ISSUE TITLE
Move away from netsurf to visurf

### ISSUE THREAD

**Issue by johsjohsjohs** [oasislinux/oasis#45]
https://drewdevault.com/2021/09/11/visurf-announcement.html
https://sr.ht/~sircmpwn/visurf/

**Comment by michaelforney** [comment]
Why? visurf has more dependencies (cairo, pango, harfbuzz, fribidi, fontconfig), the first three of which I've managed to avoid for everything else in oasis, and harfbuzz is written C++.

Do you have any problems with the oasis frontend?
