### ISSUE TITLE
Install question: Merge built system into root repository step

### ISSUE THREAD

**Issue by Eloitor** [oasislinux/oasis#49]
I'm trying to build oasis following the instructions in the wiki, but I get stuck in the step "Merge built system into root repository."

I'm on void-linux. I created a partition `/dev/sda2`, and I mounted it to `/mnt`. I changed the ownership of the folder to my user.

Then I followed the instructions on the wiki:
``` bash
sudo xbps-install -S bison curl git ninja lua pax wayland-devel libpng-devel nasm

cd /mnt
curl -O http://musl.cc/x86_64-linux-musl-cross.tgz
zcat x86_64-linux-musl-cross.tgz | pax -r

export PATH=$PATH:$PWD/x86_64-linux-musl-cross/bin
export ROOT="/mnt"
export DRIVE="sda"
export ROOTPART="sda2"
export EDITOR="nvim"

cd $ROOT
git clone -c 'core.sharedRepository=group' https://github.com/oasislinux/oasis.git src/oasis
git init --template src/oasis/template
cd src/oasis

cp config.def.lua config.lua

$EDITOR config.lua
# I changed: repo={ path='../..', flags='', tag='tree', branch='oasis', }

lua setup.lua
ninja commit

cd $ROOT
git config branch.master.remote .
git config branch.master.merge oasis
```
But then `git merge` outputs
```
merge: oasis - no és quelcom que puguem fusionar
```
and `./libexec/applyperms` outputs
```
./setup.sh: 37: ./libexec/applyperms: not found
```

I found `applyperms` in `/mnt/src/oasis/out/root.hash/libexec`, but I didn't find the executable file.

**Comment by michaelforney** [comment]
> But then git merge outputs

Can you confirm that you ran `git merge` from your root repository mounted at `/mnt` (i.e. not `/mnt/src/oasis`)?

> ```
> # I changed: repo={ path='../..', flags='', tag='tree', branch='oasis', }
> ```

Can you double-check this? This instructs the oasis build system to make commit in the `../..` repository to the branch `oasis`, but the error message indicates that there is no branch `oasis` in your root repository at `/mnt` (assuming that's where you ran `git merge` from).

**Comment by Eloitor** [comment]
Thank you, I didn't see that I left `branch=master`. Changing it to `oasis` worked.
