### ISSUE TITLE
how can I install packages in the qemu image ?

### ISSUE THREAD

**Issue by LaithOsama** [oasislinux/oasis#53]
sorry for the stupid question, but I'm really don't know how to install packages in this environment, also I didn't used to deal with lua and ninja.
Can you please tell me how to install any package from /src/oasis ?
whatever, thank you for your amazing projects.

**Comment by michaelforney** [comment]
The README in the qemu image contains a section "Rebuilding the system from source". Follow those instructions, then edit `config.lua` to include the packages you want in the `fs` table. Then, build again and merge to `/` with `samu commit && git -C / merge`.

For example, if you want to install the `sfeed` package, you might make a change like this:

```diff
-		{sets.core, sets.extra, sets.desktop, exclude={'^include/', '^lib/.*%.a$'}},
+		{sets.core, sets.extra, sets.desktop, 'sfeed', exclude={'^include/', '^lib/.*%.a$'}},
```

**Comment by LaithOsama** [comment]
Thanks mate! I didn't seen the README file there, Sorry.

God bless you.
