### ISSUE TITLE
`mandoc` is missing `less`

### ISSUE THREAD

**Issue by Sertonix** [oasislinux/oasis#55]
The package `mandoc` is in the core list and requires `less` but `less` is not in the core list.

I am new to this but I think `less` should be moved to the core list.

**Comment by hovercats** [comment]
`mandoc` may list `less` as a dependency, but in reality, it only needs something that acts as a pager. 
In any case, the default pager in Oasis is set to `cat`. Which works.
if youd rather use `less`, you can just install that,
and set that as your default pager in `/etc/profile`.

**Comment by michaelforney** [comment]
Exactly what @hovercats said.
