### ISSUE TITLE
openbsd: sources 7.1 are deleted, upgrade to 7.2

### ISSUE THREAD

**Issue by apprehensions** [oasislinux/oasis#61]
currently, as of b7fa94c171d8ab43cf78d40acf2f2d468a465026, the openbsd package's `url` file sources urls no longer exist, as they return with 404: https://fastly.cdn.openbsd.org/pub/OpenBSD/7.1/sys.tar.gz

a workaround is to use these sources: https://artfiles.org/openbsd/7.1/sys.tar.gz

**Comment by michaelforney** [comment]
Updated to 7.3
