### ISSUE TITLE
OpenBSD based userspace, using code from https://github.com/CobaltBSD/cbtutils

### ISSUE THREAD

**Issue by xplshn** [oasislinux/oasis#67]
We could replace some parts of the system using code from https://github.com/CobaltBSD/cbtutils
CBUTILS is a collection of ports from OpenBSD, and NetBSD for Linux based OSes.

**Comment by hovercats** [comment]
why? what benefit does using cbutils over the already included `openbsd` package?
from a quick glance at the project aswell as its provider, I dont really see how this would be a better fit for Oasis' goals than what is already provided with `openbsd` package aswell as other utils.

in any case, oasis is made to be easily modified, so if you so choose, you could replace `openbsd` package, and other utilities with `cbutils` if you wish.
