### ISSUE TITLE
Shared library support

### ISSUE THREAD

**Issue by nwmcsween** [oasislinux/oasis#7]
Issues:
* Generation of symlinks for lib install (e.g. /lib/libfoo-1.5, /lib/libfoo-1.5.2, ...)
* Tracking of dependencies
* RUNPATH without having to chroot
* Probably a few dozen more

**Comment by protonesso** [comment]
> statically-linked system

**Comment by michaelforney** [comment]
Yes, though it might still be desirable to support dynamic linking for a couple cases:
- Interpreted language modules (python, lua, ...)
- If I end up adding a ports-like system for heavier components, they might require dynamic linking (e.g. mesa).

But this is low-priority, so I'll just leave this open for now.

**Comment by michaelforney** [comment]
Now, the musl package provides a libc.so (if you select it for installation). This can be used to bootstrap external package systems like pkgsrc or nix. Dynamic languages with module support and heavy components that require dynamic linking can be installed that way.
