### ISSUE TITLE
Can't use make menuconfig on the kernel

### ISSUE THREAD

**Issue by vladimirlucifer** [oasislinux/oasis#72]
checklist.o throws many "undefined reference to _asc_char".
I'm trying the v6.4 checkout following the wiki, with no luck.

**Comment by vladimirlucifer** [comment]
If it helps with anything, I'm using the default environment of oasis, while also using all the predefined sets.

**Comment by vladimirlucifer** [comment]
The exact output is as follows: 

oasis# make menuconfig
cflags="-D_GNU_SOURCE"
libs="-lcurses -lterminfo"
  HOSTLD  scripts/kconfig/mconf
/bin/ld: scripts/kconfig/lxdialog/yesno.o: warning: relocation against `_acs_char' in read-only section `.text'
/bin/ld: scripts/kconfig/lxdialog/checklist.o: in function `print_arrows':
checklist.c:(.text+0x49): undefined reference to `_acs_char'
/bin/ld: checklist.c:(.text+0x98): undefined reference to `_acs_char'
/bin/ld: checklist.c:(.text+0xa6): undefined reference to `_acs_char'
/bin/ld: checklist.c:(.text+0xb4): undefined reference to `_acs_char'
/bin/ld: checklist.c:(.text+0xc2): undefined reference to `_acs_char'
/bin/ld: scripts/kconfig/lxdialog/checklist.o:checklist.c:(.text+0xf0): more undefined references to `_acs_char' follow
/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[1]: *** [scripts/Makefile.host:119: scripts/kconfig/mconf] Error 1
make: *** [Makefile:692: menuconfig] Error 2
oasis#

I can't seem to narrow down why these symbols are undefined, while the netbsd-curses library is built

**Comment by michaelforney** [comment]
This was a mistake during the v6.4 merge. It should be fixed by https://github.com/oasislinux/linux/commit/8e89a3050b930c6bf7c3e6dcc7ee3ee0f49c8ab8.
