### ISSUE TITLE
Link to QEMU Image Not Loading.

### ISSUE THREAD

**Issue by VehementHam** [oasislinux/oasis#86]
### Steps to reproduce
Click on the link. It will time out.

### Possible Solution
Realease the archive in a "Realeses" section on this git repo.

**Comment by michaelforney** [comment]
SourceHut is the target of an ongoing DDoS attack. Please give them some patience to resolve the issue.

See here for updates: https://outage.sr.ht/

**Comment by VehementHam** [comment]
In the mean time, is theree another way to obtain the image.

**Comment by rochus-keller** [comment]
The links still doesn't seem to work: https://patchouli.sr.ht/builds.sr.ht/artifacts/~mcf/898139/041f9b22bf687120/oasis-qemu.tar.xz
Is there an alternative place where I could download a QEMU image?

**Comment by michaelforney** [comment]
I just built a new one: https://s3.sr.ht/builds.sr.ht/artifacts/~mcf/1138649/ff314f9e1f24ce4f/oasis-qemu.tar.xz

Note also that the qemu build script is pretty easy to run yourself: https://github.com/oasislinux/build-qemu/blob/master/build

**Comment by rochus-keller** [comment]
Great, thanks. I'm working on an old Linux x86 system and emulate AMD64 with QEMU.
