### ISSUE TITLE
PKG - Scron

### ISSUE THREAD

**Issue by VehementHam** [oasislinux/oasis#90]
This should be an easy one: [scron](https://git.2f30.org/scron/).

**Comment by rnpnr** [comment]
This is the same cron that is already included with sbase. It looks like just the man page wasn't synced. Its not really necessary though because man-pages-posix includes `crontab(1p)`.

**Comment by VehementHam** [comment]
Right but Scron is the "simple" cron daemon. It is listed on the suckless websitek. I assumed that it is more suckless.

**Comment by rnpnr** [comment]
I mean that the code is the same.

**Comment by VehementHam** [comment]
Oh
