### ISSUE TITLE
Dvorak Does Not Exist On QEMU

### ISSUE THREAD

**Issue by VehementHam** [oasislinux/oasis#93]
# Reproduce
```sh
oasis$ export XKB_DEFAULT_LAYOUT=dvorak
oasis$ swc-launch velox
``` 
# Issue 
```               
running on /dev/tty2
xkbcommon: ERROR: Couldn't find file "symbols/dvorak" in include paths
xkbcommon: ERROR: 1 include paths searched:
xkbcommon: ERROR: 	/share/xkb
xkbcommon: ERROR: 3 include paths could not be added:
xkbcommon: ERROR: 	/home/oasis/.config/xkb
xkbcommon: ERROR: 	/home/oasis/.xkb
xkbcommon: ERROR: 	/etc/xkb
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
ERROR: Could not create XKB keymap
ERROR: Could not initialize keyboard
ERROR: Could not initialize seat
```

**Comment by michaelforney** [comment]
In XKB, Dvorak is a variant, not a layout.

```
export XKB_DEFAULT_LAYOUT=us XKB_DEFAULT_VARIANT=dvorak
swc-launch velox
```

**Comment by VehementHam** [comment]
Thanks.

**Comment by VehementHam** [comment]
After running `export XKB_DEFAULT_VARIANT=dvorak` in the shell, followed by swc-launch velox, the keybord layout does not change in velox. How do I chage the keybord layout in velox?

**Comment by apprehensions** [comment]
Did you do `export XKB_DEFAULT_LAYOUT=us XKB_DEFAULT_VARIANT=dvorak`?

**Comment by VehementHam** [comment]
Yes, I tried that too.

**Comment by michaelforney** [comment]
I'm sorry you're having trouble, but I can assure you that it does work. I type in dvorak as well. My guess is you have a typo somewhere. As @apprehensions said, you need to set both `XKB_DEFAULT_LAYOUT=us` (or whatever's appropriate for your country/language) *and* `XKB_DEFAULT_VARIANT=dvorak`. Setting just `XKB_DEFAULT_VARIANT=dvorak` won't work.

See the code:
https://github.com/xkbcommon/libxkbcommon/blob/43c9752d441702011500e562c8bbc41ec0254772/src/context-priv.c#L151-L154

**Comment by VehementHam** [comment]
Your right, it was a typo. I only noticed after the third check. I'm gonna drink some water now
