### ISSUE TITLE
valgrind and gdb

### ISSUE THREAD

**Issue by AI-dimitri** [oasislinux/oasis#97]
Dear development team! Thank you all, for this great OS!

Can you please tell me why there are no valgrind and gdb? It is very usefull programs and not have them is sad : - (

**Comment by michaelforney** [comment]
They are complicated pieces of software that would be a lot of work to package. They are both available in pkgsrc, which is how I've installed them.

Another thing to look at is `-fsanitize=address`, which is a decent substitute for valgrind that is available in the default toolchain.
